// Coffee
export enum CoffeeStatus {
  ACTIVE = 'ACTIVE',
  SOLD_OUT = 'SOLD_OUT',
  IN_STOCK = 'IN_STOCK',
  ORDERED = 'ORDERED',
  DELETED = 'DELETED',
}

// Product - Woo status
export enum ProductStatus {
  DRAFT = 'DRAFT', // Never published in Woo
  PUBLISHED = 'PUBLISHED', // Published in Woo
  PRIVATE = 'PRIVATE', // Hidden in Woo
  DELETED = 'DELETED',
}

// Product - Woo stock status
export enum ProductStockStatus {
  ON_BACKORDER = 'ON_BACKORDER',
  IN_STOCK = 'IN_STOCK',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
}

export enum ProductStockLocation {
  IN_DELIVERY = 'IN_DELIVERY',
  IN_ROASTERY = 'IN_ROASTERY',
}

// Subscription
export enum SubscriptionType {
  PRIVATE = 'PRIVATE',
  PRIVATE_GIFT = 'PRIVATE_GIFT',
  B2B = 'B2B',
}

export enum SubscriptionStatus {
  NOT_STARTED = 'NOT_STARTED',
  ACTIVE = 'ACTIVE',
  PASSIVE = 'PASSIVE',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  DELETED = 'DELETED',
}

export enum SubscriptionFrequency {
  MONTHLY = 'MONTHLY',
  MONTHLY_3RD = 'MONTHLY_3RD',
  FORTNIGHTLY = 'FORTNIGHTLY',
}

export enum SubscriptionSpecialRequest {
  NONE = 'NONE',
  TWO_COFFEE_TYPES = 'TWO_COFFEE_TYPES',
  NO_DRY_PROCESSED = 'NO_DRY_PROCESSED',
  ONLY_DRY_PROCESSED = 'ONLY_DRY_PROCESSED',
}

// Delivery
export enum DeliveryStatus {
  ACTIVE = 'ACTIVE',
  DELETED = 'DELETED',
}

// Order
export enum OrderStatus {
  ACTIVE = 'ACTIVE',
  ON_HOLD = 'ON_HOLD',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  DELETED = 'DELETED',
}

export enum OrderType {
  RENEWAL = 'RENEWAL',
  NON_RENEWAL = 'NON_RENEWAL',
  CUSTOM = 'CUSTOM',
}

export enum ShippingType {
  SHIP = 'SHIP',
  LOCAL_PICK_UP = 'LOCAL_PICK_UP',
}

// Helper to ensure enum names are stable in Postgres when generated by TypeORM migrations later
// Note: If you are not using TypeORM migrations to create enums, these calls are harmless
export const enumNames = {
  CoffeeStatus: 'CoffeeStatus',
  ProductStatus: 'ProductStatus',
  ProductStockStatus: 'ProductStockStatus',
  SubscriptionType: 'SubscriptionType',
  SubscriptionStatus: 'SubscriptionStatus',
  SubscriptionFrequency: 'SubscriptionFrequency',
  SubscriptionSpecialRequest: 'SubscriptionSpecialRequest',
  DeliveryStatus: 'DeliveryStatus',
  OrderStatus: 'OrderStatus',
  OrderType: 'OrderType',
  ShippingType: 'ShippingType',
} as const;
